export enum TipoCuenta {
  INDIVIDUAL = 'INDIVIDUAL',
  PAREJA = 'PAREJA',
}

export enum EstadoPareja {
  ACTIVA = 'ACTIVA',
  PAUSADA = 'PAUSADA',
  SEPARADA = 'SEPARADA',
}

export enum TipoDivision {
  POR_INGRESOS = 'POR_INGRESOS',
  CINCUENTA_CINCUENTA = 'CINCUENTA_CINCUENTA',
  CUSTOM = 'CUSTOM',
}

export enum NivelTransparencia {
  COMPLETO = 'COMPLETO',
  PARCIAL = 'PARCIAL',
  MINIMO = 'MINIMO',
}

export enum CategoriaGasto {
  COMIDA = 'COMIDA',
  TRANSPORTE = 'TRANSPORTE',
  ENTRETENIMIENTO = 'ENTRETENIMIENTO',
  SERVICIOS = 'SERVICIOS',
  COMPRAS = 'COMPRAS',
  SALUD = 'SALUD',
  EDUCACION = 'EDUCACION',
  VIAJES = 'VIAJES',
  HOGAR = 'HOGAR',
  MASCOTAS = 'MASCOTAS',
  REGALOS = 'REGALOS',
  IMPUESTOS = 'IMPUESTOS',
  OTROS = 'OTROS',
}

export enum TipoGasto {
  PERSONAL = 'PERSONAL',
  COMPARTIDO = 'COMPARTIDO',
  ADELANTO = 'ADELANTO',
  REEMBOLSO = 'REEMBOLSO',
}

export enum NivelPrivacidad {
  COMPLETO = 'COMPLETO',
  CATEGORIA_SOLO = 'CATEGORIA_SOLO',
  OCULTO = 'OCULTO',
}

export enum FuenteRegistro {
  FOTO_GEMMA = 'FOTO_GEMMA',
  CHAT = 'CHAT',
  VOZ = 'VOZ',
  MANUAL = 'MANUAL',
  IMPORTADO = 'IMPORTADO',
  RECURRENTE = 'RECURRENTE',
}

export enum TipoCartera {
  BILLETERA_DIGITAL = 'BILLETERA_DIGITAL',
  BANCO_AHORROS = 'BANCO_AHORROS',
  BANCO_CORRIENTE = 'BANCO_CORRIENTE',
  TARJETA_CREDITO = 'TARJETA_CREDITO',
  TARJETA_DEBITO = 'TARJETA_DEBITO',
  EFECTIVO = 'EFECTIVO',
  INVERSION = 'INVERSION',
  CRIPTO = 'CRIPTO',
  OTRO = 'OTRO',
}

export enum TipoMeta {
  AHORRO = 'AHORRO',
  GASTO_LIMITE = 'GASTO_LIMITE',
  INGRESO = 'INGRESO',
  DEUDA = 'DEUDA',
}

export enum EstadoMeta {
  ACTIVA = 'ACTIVA',
  COMPLETADA = 'COMPLETADA',
  PAUSADA = 'PAUSADA',
  CANCELADA = 'CANCELADA',
}

export enum TipoNotificacion {
  GASTO_REGISTRADO = 'GASTO_REGISTRADO',
  PAREJA_VINCULADA = 'PAREJA_VINCULADA',
  META_ALCANZADA = 'META_ALCANZADA',
  PRESUPUESTO_EXCEDIDO = 'PRESUPUESTO_EXCEDIDO',
  RECORDATORIO_PAGO = 'RECORDATORIO_PAGO',
  GASTO_INUSUAL = 'GASTO_INUSUAL',
  RESUMEN_MENSUAL = 'RESUMEN_MENSUAL',
}
